services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVER_ADDRESS=:8081
      - ALLOWED_ORIGINS=*,http://localhost:3000
      - JWT_SECRET_KEY=hoge
    volumes:
      - go-modules:/go/pkg/mod

volumes:
  go-modules:
